site_name: scimpler
site_description: simpler SCIM integrations
site_author: Arkadiusz Pajor
repo_url: https://github.com/Pagerous/scimple
repo_name: scimpler
nav:
  - Introduction: index.md
  - User's Guide: users_guide.md
  - API Reference:
      - scimpler.data:
          - AttrFilter: api_reference/scimpler_data/attr_filter.md
          - AttrName: api_reference/scimpler_data/attr_name.md
          - AttrValuePresenceConfig: api_reference/scimpler_data/attr_value_presence_config.md
          - Attribute: api_reference/scimpler_data/attribute.md
          - AttributeWithCaseExact: api_reference/scimpler_data/attribute_with_case_exact.md
          - AttributeWithUniqueness: api_reference/scimpler_data/attribute_with_uniqueness.md
          - AttrRep: api_reference/scimpler_data/attr_rep.md
          - AttrRepFactory: api_reference/scimpler_data/attr_rep_factory.md
          - Attrs: api_reference/scimpler_data/attrs.md
          - Binary: api_reference/scimpler_data/binary.md
          - Boolean: api_reference/scimpler_data/boolean.md
          - BoundedAttrRep: api_reference/scimpler_data/bounded_attr_rep.md
          - BoundedAttrs: api_reference/scimpler_data/bounded_attrs.md
          - Complex: api_reference/scimpler_data/complex.md
          - DateTime: api_reference/scimpler_data/datetime.md
          - Decimal: api_reference/scimpler_data/decimal.md
          - ExternalReference: api_reference/scimpler_data/external_reference.md
          - Filter: api_reference/scimpler_data/filter.md
          - Integer: api_reference/scimpler_data/integer.md
          - PatchPath: api_reference/scimpler_data/patch_path.md
          - ResourceSchema: api_reference/scimpler_data/resource_schema.md
          - SchemaExtension: api_reference/scimpler_data/schema_extension.md
          - SchemaUri: api_reference/scimpler_data/schema_uri.md
          - ScimData: api_reference/scimpler_data/scim_data.md
          - ScimReference: api_reference/scimpler_data/scim_reference.md
          - String: api_reference/scimpler_data/string.md
          - Sorter: api_reference/scimpler_data/sorter.md
          - UriReference: api_reference/scimpler_data/uri_reference.md
      - scimpler.data.operator:
          - And: api_reference/scimpler_data_operator/and.md
          - BinaryAttributeOperator: api_reference/scimpler_data_operator/binary_attribute_operator.md
          - ComplexAttributeOperator: api_reference/scimpler_data_operator/complex_attribute_operator.md
          - Contains: api_reference/scimpler_data_operator/contains.md
          - EndsWith: api_reference/scimpler_data_operator/ends_with.md
          - Equal: api_reference/scimpler_data_operator/equal.md
          - GreaterThan: api_reference/scimpler_data_operator/greater_than.md
          - GreaterThanOrEqual: api_reference/scimpler_data_operator/greater_than_or_equal.md
          - LesserThan: api_reference/scimpler_data_operator/lesser_than.md
          - LesserThanOrEqual: api_reference/scimpler_data_operator/lesser_than_or_equal.md
          - Not: api_reference/scimpler_data_operator/not.md
          - NotEqual: api_reference/scimpler_data_operator/not_equal.md
          - Or: api_reference/scimpler_data_operator/or.md
          - Present: api_reference/scimpler_data_operator/present.md
          - StartsWith: api_reference/scimpler_data_operator/starts_with.md
          - UnaryAttributeOperator: api_reference/scimpler_data_operator/unary_attribute_operator.md
      - scimpler.error:
          - ValidationError: api_reference/scimpler_error/validation_error.md
          - ValidationIssues: api_reference/scimpler_error/validation_issues.md
          - ValidationWarning: api_reference/scimpler_error/validation_warning.md
      - scimpler.ext:
          - marshmallow: api_reference/scimpler_ext/marshmallow.md
      - scimpler.query_string:
          - ResourceObjectGet: api_reference/scimpler_query_string/resource_object_get.md
          - ResourceObjectPatch: api_reference/scimpler_query_string/resource_object_patch.md
          - ResourceObjectPut: api_reference/scimpler_query_string/resource_object_put.md
          - ResourceTypesGet: api_reference/scimpler_query_string/resource_types_get.md
          - ResourcesGet: api_reference/scimpler_query_string/resources_get.md
          - ResourcesPost: api_reference/scimpler_query_string/resources_post.md
          - SchemasGet: api_reference/scimpler_query_string/schemas_get.md
      - scimpler.schemas:
          - BulkRequestSchema: api_reference/scimpler_schemas/bulk_request_schema.md
          - BulkResponseSchema: api_reference/scimpler_schemas/bulk_response_schema.md
          - EnterpriseUserSchemaExtension: api_reference/scimpler_schemas/enterprise_user_schema_extension.md
          - ErrorSchema: api_reference/scimpler_schemas/error_schema.md
          - GroupSchema: api_reference/scimpler_schemas/group_schema.md
          - ListResponseSchema: api_reference/scimpler_schemas/list_response_schema.md
          - PatchOpSchema: api_reference/scimpler_schemas/patch_op_schema.md
          - ResourceTypeSchema: api_reference/scimpler_schemas/resource_type_schema.md
          - SchemaDefinitionSchema: api_reference/scimpler_schemas/schema_definition_schema.md
          - SearchRequestSchema: api_reference/scimpler_schemas/search_request_schema.md
          - ServiceProviderConfigSchema: api_reference/scimpler_schemas/service_provider_config_schema.md
          - UserSchema: api_reference/scimpler_schemas/user_schema.md
      - scimpler.validator:
          - BulkOperations: api_reference/scimpler_validator/bulk_operations.md
          - Error: api_reference/scimpler_validator/error.md
          - ResourceObjectDelete: api_reference/scimpler_validator/resource_object_delete.md
          - ResourceObjectGet: api_reference/scimpler_validator/resource_object_get.md
          - ResourceObjectPatch: api_reference/scimpler_validator/resource_object_patch.md
          - ResourceObjectPut: api_reference/scimpler_validator/resource_object_put.md
          - ResourcesPost: api_reference/scimpler_validator/resources_post.md
          - ResourcesQuery: api_reference/scimpler_validator/resources_query.md
          - SearchRequestPost: api_reference/scimpler_validator/search_request_post.md
      - scimpler.config: api_reference/scimpler_config.md

  - Compliance: compliance.md
theme: material
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_root_toc_entry: True
            show_root_heading: false
            show_root_full_path: true
            show_category_heading: true
            show_labels: true
            show_bases: true
            handler: python
            docstring_section_style: spacy
            show_signature: true
            signature_crossrefs: true
            relative_crossrefs: true
            scoped_crossrefs: true
            inherited_members: true
            parameter_headings: true
            merge_init_into_class: true

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg