site_name: scimpler
site_description: simpler SCIM integrations
site_author: Arkadiusz Pajor
repo_url: https://github.com/Pagerous/scimple
repo_name: scimpler
nav:
  - Introduction: index.md
  - User's Guide: users_guide.md
  - API Reference: api_reference.md
  - Compliance: compliance.md
theme: material
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg