[tool.poetry]
name = "scimpler"
version = "0.1.0"
description = ""
authors = ["Arkadiusz Pajor <arkadiuszpajor97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
marshmallow = {version = "^3.21.1", optional = true}
precis-i18n = "^1.1.0"
phonenumbers = "^8.13.35"
iso3166 = "^2.1.1"
typing-extensions = "^4.12.2"

[tool.poetry.extras]
marshmallow = ["marshmallow"]

[tool.poetry.group.dev.dependencies]
pytest = "^8"
pytest-cov = "^4.1.0"
mypy = "^1.10.0"
ruff = "^0.4.8"
ipython = "^8.18.1"

[tool.pytest.ini_options]
pythonpath = "src"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    # Pyflakes
    "F",
    # pycodestyle
    "E", "W",
    # pep8-naming
    "N",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-datetime
    "DTZ",
    # flake8-pie
    "PIE",
    # flake8-pytest-style
    "PT",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pylint
    "PL",
]

ignore = [
    "PT004",  # pytest-missing-fixture-name-underscore
    "PT005",  # pytest-incorrect-fixture-name-underscore
    "B009",  # get-attr-with-constant
    "B010",  # set-attr-with-constant
    "N818",  # error-suffix-on-exception-name
    "PLC0414", # useless-import-alias; conflicting with F401 recommendation
    "PLR0913",  # too-many-args
    "PLW2901",
    "PLR2004",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/test_*.py" = [
    "PLR2004",  # magic-value-comparison
    "E501",  # line-too-long; it's better for test names to be explanatory enough
    "DTZ",  # if code has date/time issues, the test must follow
    "PLR0913",  # too-many-arguments; complex tests accept many fixutres and that's fine
]

[tool.ruff.lint.flake8-pytest-style]
fixture-parentheses = false
