from src.data.attributes import (
    AttributeIssuer,
    AttributeMutability,
    Boolean,
    Complex,
    String,
    URIReference,
)
from src.data.schemas import ServiceResourceSchema

ResourceType = ServiceResourceSchema(
    schema="urn:ietf:params:scim:schemas:core:2.0:ResourceType",
    name="ResourceType",
    endpoint="/ResourceTypes",
    attrs=[
        String(
            name="id",
            mutability=AttributeMutability.READ_ONLY,
            issuer=AttributeIssuer.SERVER,
        ),
        String(
            name="name",
            mutability=AttributeMutability.READ_ONLY,
            issuer=AttributeIssuer.SERVER,
            required=True,
        ),
        String(
            name="description",
            mutability=AttributeMutability.READ_ONLY,
            issuer=AttributeIssuer.SERVER,
        ),
        URIReference(
            name="endpoint",
            mutability=AttributeMutability.READ_ONLY,
            issuer=AttributeIssuer.SERVER,
            required=True,
        ),
        String(
            name="schema",
            mutability=AttributeMutability.READ_ONLY,
            issuer=AttributeIssuer.SERVER,
            required=True,
        ),
        Complex(
            sub_attributes=[
                String(
                    name="schema",
                    mutability=AttributeMutability.READ_ONLY,
                    issuer=AttributeIssuer.SERVER,
                    required=True,
                ),
                Boolean(
                    name="required",
                    mutability=AttributeMutability.READ_ONLY,
                    issuer=AttributeIssuer.SERVER,
                    required=True,
                ),
            ],
            name="schemaExtensions",
            multi_valued=True,
        ),
    ],
)
