from src.data.attributes import (
    AttributeIssuer,
    AttributeMutability,
    AttributeReturn,
    AttributeUniqueness,
    Boolean,
    Complex,
    ExternalReference,
    Integer,
    String,
)
from src.data.schemas import ServiceResourceSchema, bulk_id_validator

ServiceProviderConfig = ServiceResourceSchema(
    schema="urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig",
    name="ServiceProviderConfig",
    endpoint="/ServiceProviderConfig",
    attrs=[
        String(
            name="id",
            required=False,
            issuer=AttributeIssuer.SERVER,
            case_exact=True,
            multi_valued=False,
            mutability=AttributeMutability.READ_ONLY,
            returned=AttributeReturn.ALWAYS,
            uniqueness=AttributeUniqueness.SERVER,
            validators=[bulk_id_validator],
        ),
        ExternalReference(
            name="documentationUri",
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            name="patch",
            sub_attributes=[
                Boolean(
                    name="supported",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                )
            ],
            required=True,
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            name="bulk",
            sub_attributes=[
                Boolean(
                    name="supported",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
                Integer(
                    name="maxOperations",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
                Integer(
                    name="maxPayloadSize",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
            ],
            required=True,
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            name="filter",
            sub_attributes=[
                Boolean(
                    name="supported",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
                Integer(
                    name="maxResults",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
            ],
            required=True,
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            name="changePassword",
            sub_attributes=[
                Boolean(
                    name="supported",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                )
            ],
            required=True,
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            name="sort",
            sub_attributes=[
                Boolean(
                    name="supported",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                )
            ],
            required=True,
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            sub_attributes=[
                Boolean(
                    name="supported",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                )
            ],
            name="etag",
            required=True,
            mutability=AttributeMutability.READ_ONLY,
        ),
        Complex(
            name="authenticationSchemes",
            sub_attributes=[
                String(
                    name="type",
                    required=True,
                    canonical_values=[
                        "oauth",
                        "oauth2",
                        "oauthbearertoken",
                        "httpbasic",
                        "httpdigest",
                    ],
                    mutability=AttributeMutability.READ_ONLY,
                ),
                String(
                    name="name",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
                String(
                    name="description",
                    required=True,
                    mutability=AttributeMutability.READ_ONLY,
                ),
                ExternalReference(
                    name="specUri",
                    mutability=AttributeMutability.READ_ONLY,
                ),
                ExternalReference(
                    name="specUri",
                    mutability=AttributeMutability.READ_ONLY,
                ),
            ],
            multi_valued=True,
            mutability=AttributeMutability.READ_ONLY,
            required=True,
        ),
    ],
)
