name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linters_check:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies with Poetry
      run: |
        poetry install -E marshmallow

    - name: Run mypy
      run: |
        poetry run mypy .

    - name: Run ruff check
      run: |
        poetry run ruff check .

    - name: Run ruff format check
      run: |
        poetry run ruff check . --fix --diff

    - name: Run isort check
      run: |
        poetry run isort . --check --diff

  tests:
    name: Test code for supported Python versions
    needs: [linters_check]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@7b6d33e44b4f08d7021a1dee3c044e9c253d6439 # v3
      - name: Install environment
        run: poetry install -E marshmallow
      - name: Run tests
        run: poetry run pytest --cov=src --cov-fail-under=99
